# Copyright (c) 2023 VEXXHOST, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

# NOTE(mnaser): This playbook is strictly used for testing purposes, it creates
#               a few volume groups which can be used to create OSDs.

- name: Destroy devices for Ceph
  hosts: "{{ ceph_osd_group | default('cephs') }}"
  ignore_errors: true
  become: true
  tasks:
    - name: Shutdown all OSDs
      ansible.builtin.service:
        name: ceph-osd.target
        state: stopped

    - name: Get list of all loopback devices
      ansible.builtin.shell: losetup -J
      changed_when: false
      register: _losetup_l

    - name: Delete a logical volume for each loop device
      community.general.lvol:
        vg: ceph-{{ inventory_hostname_short }}-{{ item['back-file'].split('/')[-1].split('.')[0] }}
        lv: data
        force: true
        state: absent
      loop: "{{ _losetup_l.stdout | default('{}', true) | from_json | json_query('loopdevices[?starts_with(\"back-file\", `/opt/osd`)].{name: name, \"back-file\": \"back-file\"}') | default([], true) }}"

    - name: Delete a volume group for each loop device
      community.general.lvg:
        vg: ceph-{{ inventory_hostname_short }}-{{ item['back-file'].split('/')[-1].split('.')[0] }}
        state: absent
      loop: "{{ _losetup_l.stdout | default('{}', true) | from_json | json_query('loopdevices[?starts_with(\"back-file\", `/opt/osd`)].{name: name, \"back-file\": \"back-file\"}') | default([], true) }}"

    - name: Stop loopback devices for unmapped images
      ansible.builtin.command: losetup -d {{ item.name }}
      loop: "{{ _losetup_l.stdout | default('{}', true) | from_json | json_query('loopdevices[?starts_with(\"back-file\", `/opt/osd`)].{name: name, \"back-file\": \"back-file\"}') | default([], true) }}"
